name: google_maps
version: 6.2.0
description: >
  With that package you will be able to use Google Maps JavaScript API from Dart
  scripts.
homepage: https://github.com/a14n/dart-google-maps
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  js_wrapping: ^0.7.4
  meta: ^1.3.0
dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  collection: ^1.16.0
  dart_style: ^2.0.0
  html: ^0.15.0
  http: ^0.13.0
  js_wrapping_generator: ^0.7.3
  path: ^1.7.0
# dependency_overrides:
#   js_wrapping:
#     # git:
#     #   url: https://github.com/a14n/dart-js-wrapping.git
#     #   ref: master
#     #   path: js_wrapping
#     path: ../dart-js-wrapping/js_wrapping
#   js_wrapping_generator:
#     # git:
#     #   url: https://github.com/a14n/dart-js-wrapping.git
#     #   ref: master
#     #   path: js_wrapping_generator
#     path: ../dart-js-wrapping/js_wrapping_generator
