version: '1'

services:
  dbpostgresql:
    container_name: postgres_b
    image: "postgres"
    ports:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - banca
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      restart: unless-stopped
  app:
    build: .
    image: banca
    container_name: banca
    ports:
      - "8088:8088"
    depends_on:
      - dbpostgresql
    networks:
      - banca
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
volumes:
  db-data:
  pgadmin-data:
networks:
  banca:
    driver: bridge
# docker-compose build && docker-compose up