version: '3'

services:
  dbpostgresql:
    container_name: postgres
    image: "postgres"
    ports:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - gestore-credenziali
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      restart: unless-stopped
  app:
    build: .
    image: gestore-credenziali
    container_name: gestore-credenziali
    ports:
      - "8085:8085"
    depends_on:
      - dbpostgresql
    networks:
      - gestore-credenziali
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
volumes:
  db-data:
  pgadmin-data:
networks:
  gestore-credenziali:
    driver: bridge
# docker-compose build && docker-compose up